### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [iotaledger/identity.rs#1156]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by eike-hass** [comment]
Hello @igibek 👋 
Thank you for reaching out! Please follow the responsible disclosure process described [here](https://github.com/iotaledger/identity.rs/security/policy) so we can appropriately deal with the issue on an organisational level.

**Comment by eike-hass** [comment]
@igibek, did you manage to raise a report through the describes process?
We will close this issue in ~2 weeks if there is no further activity.

**Comment by eike-hass** [comment]
closing as there was further interaction
