### ISSUE TITLE
Add JSON Web Signature 2020 suite

### ISSUE THREAD

**Issue by l1h3r** [iotaledger/identity.rs#118]
Add a signature suite with the following properties:

- [ ] Limited set of JOSE algorithms.
- [ ] Normalise signed data using ~JCS~ [RDF](http://json-ld.github.io/normalization/spec/).
- [ ] Signatures are JWS tokens with detached content.
- [ ] Public keys are stored as JSON Web Keys (JWK).
- [ ] Support [JSON Web Signature 2020](https://w3c-ccg.github.io/lds-jws2020/)

Related to #939.

**Comment by cycraig** [comment]
Changing this issue away from implementing `JcsJoseSignature2021` in favour of the existing `JsonWebSignature2020`, which is similar apart from the canonicalisation algorithm being RDF rather than JCS. This is to better align with the larger ecosystem.
