### ISSUE TITLE
[Bug] : Testnet for DID?

### ISSUE THREAD

**Issue by drtwodog** [iotaledger/identity.rs#1263]
Hey,

according to the DID examples i tried to create a DID ... but it directly throws that error...:
  
   "@iota/identity-wasm": "^1.0.0",
   "@iota/sdk-wasm": "^1.0.5",

API_ENDPOINT = "https://api.testnet.shimmer.network";

        const client = new Client({
            primaryNode: process.env.API_ENDPOINT,
            localPow: true,
        });

**Error**:  data did not match any variant of untagged enum NodeDto at line 1 column 75

**Comment by abdulmth** [comment]
I think we need more details about how you run the example, in what environment do you run the example? and is that the full error message you're getting?

**Comment by drtwodog** [comment]
Hey, ok... 

I setup a nodejs express surrounding on Ubuntu 18 
And yes, that is all I get as an error. 

I just copied your Sourcecode to create a did in the shimmer testnet... by the way, I testen it my own private net with the same error...

What parameters do you need more??

Regards

**Comment by abdulmth** [comment]
I tried to make a node.js project on Ubuntu and it seems to work fine, see https://github.com/abdulmth/create_did_example maybe try to run this project locally and see if you encounter the same error.

**Comment by drtwodog** [comment]
Thanks , i´ve got my issue -> I had installed @iota/sdk-wasm (from further tests). I´ve deinstalled and there it is .

Thanks a lot!
