### ISSUE TITLE
Communications Specification

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#136]
Research and design the message exchanges between different IOTA Identity powered actors. Write out a specification for all different exchanges between actors such as DID Authentication, Verifiable Presentation, request for Verifiable Credentials etc... 
The specification is a pre-requisite for the implementation of an actor who eventually will be able to handle all of the flows.

Prior Art:
* https://identity.foundation/didcomm-messaging/spec/
* [Jolocom Interaction Flows](https://jolocom.github.io/jolocom-sdk/1.0.0/guides/interaction_flows/)
* [Hyperledger Aries RFCs](https://github.com/hyperledger/aries-rfcs) such as:
  * [DID Exchange](https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange)
  * [Issuer Credential](https://github.com/hyperledger/aries-rfcs/tree/master/features/0453-issue-credential-v2)
  * [Present Proof](https://github.com/hyperledger/aries-rfcs/tree/master/features/0454-present-proof-v2)

**Comment by Aconitin** [comment]
(WIP, IGNORE FOR NOW)

Open questions for discussion in the standup(s):

- Authentication Request:Request: Do we need an ID?
- Authentication Request:Request: Do we need a timestamp?
- Authentication Request:Request: Do we need any other field(s)?
- Authentication Request:Response: What exactly do we sign, description or everything?
- Authentication Request:Response: Do we need any other fields?
