### ISSUE TITLE
Enforce Key Collection max size

### ISSUE THREAD

**Issue by l1h3r** [iotaledger/identity.rs#145]
Add a maximum size to the `KeyCollection` type and Merkle Key Collection operations to avoid accidentally create unrevokable keys

- Consider limitations of [roaring bitmaps](https://github.com/RoaringBitmap/RoaringFormatSpec)
- Consider limitations of [Stronghold](https://github.com/iotaledger/stronghold.rs)

**Comment by JelleMillenaar** [comment]
In addition, the parameter for creating a key collection currently is a number for the amount of keys inside the key collection, where only power of 2 numbers are allowed. We should change this such that it either only allows power of 2, or it references the depth of the Merkle tree. The latter means that when you supply "4", the Merkle Key Collection would generated 2^4 = 16 keys.
