### ISSUE TITLE
[Task] Don't run build-and-test Action on documentation PRs

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#184]
## Description
Describe the task, this may be scoped beyond a single PR.

Change the Github action for "build-and-test" to ignore PRs that contain only documentation changes. It was already done via a ` paths-ignore: - 'docs/**' ` but this may either be extended by adding preferably `**.md` to paths-ignore or otherwise adding a `branches-ignore: docs/**`. The latter is more developer error-prone, so the former is the preferred solution. We might want to check that the former solution actually doesn't ignore larger PRs that have both code changes and .md changes. 

## Motivation
Describe the motivation for the feature to be developed.

Unnessacary Github actions execution costs resources, time and this solution would be a temporary workaround for #183 

## Resources
Link to any resources relevant for the task such as Issues, PRs, reference implementations, or specifications.

- [paths-ignore](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths)
- [branches-ignore](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#excluding-branches-and-tags)

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [x] Update CI
- [ ] Test that it doesn't execute build-and-run with only .md changes
- [ ] Test that it does execute build-and-run with .md changes AND other code changes

**Comment by l1h3r** [comment]
CI Update: https://github.com/iotaledger/identity.rs/pull/241

**Comment by JelleMillenaar** [comment]
@eike-hass This is implemented, right? Please close if it is :)

**Comment by eike-hass** [comment]
yes this was solved through the inverse:
```
 pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/workflows/build-and-test.yml'
      - '**.rs'
      - '**.toml'
```
so it would only run changes to `.rs` and `.toml` files
