### ISSUE TITLE
WASM service binding

### ISSUE THREAD

**Issue by sdellava** [iotaledger/identity.rs#224]
## Description
service.rs lib is not bind with wasm

## Motivation
service  binding is required to add service point to a DID

## Are you planning to do it yourself in a pull request?

No

**Comment by Druelik** [comment]
PR#212 should fix this.

**Comment by l1h3r** [comment]
Thanks @sdellava - https://github.com/iotaledger/identity.rs/pull/212 does make the `Service` type available in WASM and we have an existing issue that you can follow/comment https://github.com/iotaledger/identity.rs/issues/194

**Comment by sdellava** [comment]
Perfect. Tnx
