### ISSUE TITLE
[Bug] Network is only using testnet

### ISSUE THREAD

**Issue by Druelik** [iotaledger/identity.rs#238]
## Bug description
The identity-iota network class is only using the testnet

## IOTA Identity version
Which version of IOTA Identity are you using?
dev branch

## Steps To reproduce the bug
Explain how the maintainer can reproduce the bug.

https://github.com/iotaledger/identity.rs/blob/dev/identity-iota/src/client/network.rs

## Expected behaviour
Default behavior should use mainnet

## Actual behaviour
uses testnet

## Errors
running the examples point to this url -> https://explorer.iota.org/chrysalis/message/7f58fb6044511b4105a1ea4a8f64418502f295e6373e49e6c8ecf37cdbdf64ad
should be -> https://explorer.iota.org/testnet/message/7f58fb6044511b4105a1ea4a8f64418502f295e6373e49e6c8ecf37cdbdf64ad 

## Will you fix it?
Yes, will do a PR.

**Comment by l1h3r** [comment]
Fixed in https://github.com/iotaledger/identity.rs/pull/242
