### ISSUE TITLE
[Bug] Rust Diff chain example panics

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#256]
## Bug description
Briefly describe the bug.

The rust example `diff_chain` panics. 

## Errors
Paste any errors that you see, including logs, errors, or screenshots.

```
thread 'main' panicked at 'assertion failed: document.verify().is_ok(), identity.rs_branch2\identity-iota\src\client\client.rs:107:5'
```

**Comment by cycraig** [comment]
The examples have changed since this issue was opened and all of them run without panics or errors right now. 

Closing this issue.
