### ISSUE TITLE
[Bug] Imports broke for identity-wasm/web

### ISSUE THREAD

**Issue by daniel-mader** [iotaledger/identity.rs#338]
## Bug description
imports broke from identity-wasm **/web** due to `import.meta.url`

## IOTA Identity version
- Version (version number, commit, or branch): @iota/identity-wasm@dev (v0.3.4)

## Steps To reproduce the bug

1. `import` anything from `"@iota/identity-wasm/web"`
2. `await init("identity_wasm_bg.wasm");`
3. when using the import, you'll get the error message below

## Errors
```
./node_modules/@iota/identity-wasm/web/identity_wasm.js 3465:51
Module parse failed: Unexpected token (3465:51)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| async function initWasm(input) {
|   if (typeof input === 'undefined') {
>     input = new URL('identity_wasm_bg.wasm', import.meta.url);
|   }
|
```

## Temporary local fix
It seems like the base URL part `import.meta.url` is causing the problem.
I was able to get it running by simply removing line `node_modules/@iota/identity-wasm/web/identity_wasm.js:3063` that throws the error. It will fallback to the default path and everything loads fine.

**Comment by abdulmth** [comment]
It seems that it's babel configuration issue in your project since the version you use works fine (without using babel). Did you try this babel plugin? [babel-plugin-syntax-import-meta](https://babeljs.io/docs/en/babel-plugin-syntax-import-meta.html)

**Comment by daniel-mader** [comment]
Thanks for the quick reply!

I tried installing the babel plugin you mentioned into my React app (create-react-app). As I might not be the only one trying to get `identity-wasm/web` working in the browser in a React app, here's what I did (I just followed the docs of **customize-cra** to add a babel-plugin to a React app):

* install [customize-cra](https://github.com/arackaf/customize-cra) and [react-app-rewired](https://github.com/timarney/react-app-rewired)
* add a `.babelrc` and define the plugin [babel-plugin-syntax-import-meta](https://babeljs.io/docs/en/babel-plugin-syntax-import-meta.html)
* add a `config-overrides.js` that lets you load your `.babelrc` with the plugin
* use `react-app-rewired` instead of `react-scripts` in the project's `package.json`

Unfortunately, still getting the same error ...

What framework / setup do you use to run **identity-wasm** in the browser? Did you get it to run in a React app?

**Comment by cycraig** [comment]
Looking online, this seems like a general issue with webpack support for `import.meta`, as per this issue: https://github.com/webpack/webpack/issues/6719

I reproduced the error using the [starter React template](https://reactjs.org/docs/create-a-new-react-app.html); adding the [webpack-import-meta-loader
](https://www.npmjs.com/package/@open-wc/webpack-import-meta-loader) package and updating the webpack configuration seems to work.

Steps I followed:

1. `npx create-react-app my-app`
2. `cd my-app`
3. `npm install @iota/identity-wasm@dev`
4. `npm install @open-wc/webpack-import-meta-loader`
5. Following the instructions from [webpack-import-meta-loader](https://www.npmjs.com/package/@open-wc/webpack-import-meta-loader), edit the webpack configuration at `node_modules/react-scripts/config/webpack.config.js` by prepending the following to the list of `rules` under `module`:

```
{
  test: /\.js$/,
  loader: require.resolve('@open-wc/webpack-import-meta-loader'),
},
```

Then `import { init } from '@iota/identity-wasm/web';` in `App.js` seems to work without any errors.

There does seem to be code in [`wasm/bindings/build/web.js`](https://github.com/iotaledger/identity.rs/blob/40790f6b130fed32e6cbf1a4aaa0c5e95f4a0897/bindings/wasm/build/web.js) to work around that, not sure if it's relevant to this issue, however:

```Javascript
// comment out this code so it works for Webpack
let changedFile = entryFile.replace(
    "input = import.meta.url.replace(",
    "// input = import.meta.url.replace("
```

P.S. I have zero experience with React or how one is supposed to override/edit the webpack configuration properly.

**Comment by daniel-mader** [comment]
I was just wondering if we're talking about dead code anyway ...

The function we're talking about is named `initWasm()` and is called at only one place which is at the very bottom of the file `@iota/identity-wasm/web/identity_wasm.js` like this:

```
return initWasm(path || 'identity_wasm_bg.wasm').then(() => {
    __initializedIotaWasm = true
    return wasm
})
```

So `initWasm()` is never called without a value and the branch `typeof input === 'undefined'` will never be true.

**--> One can remove the line containing `import.meta.url` entirely without any effect as the code branch is never hit.**

Here's a link to the source (this repo): [bindings/wasm/build/web.js#L23](https://github.com/iotaledger/identity.rs/blob/40790f6b130fed32e6cbf1a4aaa0c5e95f4a0897/bindings/wasm/build/web.js#L23)

**Comment by cycraig** [comment]
> --> One can remove the line containing import.meta.url entirely without any effect as the code branch is never hit.

I agree with this, it's just generated code and it looks like [bindings/wasm/build/web,js](https://github.com/iotaledger/identity.rs/blob/40790f6b130fed32e6cbf1a4aaa0c5e95f4a0897/bindings/wasm/build/web.js) was meant to to work around this exact issue.

The core issue seems to be with `webpack` but since we had a workaround we may as well keep it updated. I opened PR #340 with a fix.

**Comment by cycraig** [comment]
The fix will be part of the next version of `@iota/identity-wasm@dev` published to npm.

Thank you for reporting the bug.
