### ISSUE TITLE
[Bug] WASM bindings not compatible with React-Native app

### ISSUE THREAD

**Issue by JonasHiltl** [iotaledger/identity.rs#362]
## Bug description
I have just tried to use the wasm bindings in a react-native project. To get access to node modules like `fs` which are required in the bindings I setup my project with [rn-nodeify](https://www.npmjs.com/package/rn-nodeify)  which is a work-around to use node modules in an react-native app. But I stumbled on an error that prevents a react-native app from using the bindings.

React native is incompatible with the bindings because the bindings have a dynamic require in the `identity_wasm.js` file at line 10:
```javascript
//identity_wasm.js line 10
const { TextDecoder, TextEncoder, inspect } = require(String.raw`util`);
```
This is not supported by metro (The javscript bundler for RN) which makes the bindings incompatible with react native.

## Versions
@iota/identity-wasm 0.3.1

## Steps To reproduce the bug
I have setup an example app that throws the error by startup. To reproduce the bug you will need to have the [dev environment](https://reactnative.dev/docs/environment-setup) for react native setup.
```
git clone https://github.com/JonasHiltl/DigitalIdentityNodeified.git
cd ./DigitalIdentityNodeified
npm install
npx react-native start
npx react-native run-android
```
## Expected behaviour
It would be great to achieve compatibility with react native which would allow us to build apps to interact directly with the identity library without having to call a node.js backend. 

## Errors
`Error: Dynamic require defined at line 10; not supported by Metro`

**Comment by JonasHiltl** [comment]
I just did some more research and this is more of a react-native problem and it's inability to access node modules. I'm able to require the [util](https://www.npmjs.com/package/util) package after installing it manually via npm. But there are also other issues like that `TextDecoder` and `TextEncoder` are not included in this package. So I used  [fastestsmallesttextencoderdecoder](https://www.npmjs.com/package/fastestsmallesttextencoderdecoder) to make them accessible globally via a polyfill, which worked.  

An issue I couldn't find a work-around for is that the [BigUint64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array#browser_compatibility) is not available in react-native, only in Browser and Node.js. It is used in the bindings which probably makes it impossible to use the bindings in a React-native project.

**Comment by PhilippGackstatter** [comment]
Thanks for the report!

> the BigUint64Array is not available in react-native

What error are you getting? I haven't developed with React Native before, but according to the docs, the JS runtime for React Native is `JavaScriptCore`, which implements the ECMAScript standard and thus should also [support](https://262.ecma-international.org/12.0/#sec-constructor-properties-of-the-global-object-biguint64array) BigUint64Array, right :thinking:?

**Comment by JonasHiltl** [comment]
I get the error `ReferenceError: Can't find variable: BigUint64Array` and the line below is the conflicting one:
```javascript
//identity_wasm.js line 290
const uint64CvtShim = new BigUint64Array(u32CvtShim.buffer);
```

**Comment by PhilippGackstatter** [comment]
Turns out we had this problem sometime ago internally as well. The `0.3.1` version you're using is our `main` branch, which got its last update in May. The problem has since been fixed in the `dev` branch. You can use the dev tag on npm to use [the newer version](https://www.npmjs.com/package/@iota/identity-wasm/v/0.3.6).

**Comment by JonasHiltl** [comment]
When using version `0.3.6` I now get the error  `ReferenceError: Can't find variable: BigInt64Array`, because in the new version  `BigUint64Array` got replaced with `BigInt64Array`.

**Comment by PhilippGackstatter** [comment]
Sorry for the troubles. Looks like we reintroduced the problem recently. We'll get started on a fix right away.

**Comment by PhilippGackstatter** [comment]
Version `0.3.7` is on npm now, and no longer requires any `BigInt*` or `BigUint*` imports, which should hopefully fix your issue.
