### ISSUE TITLE
[Bug] VerifiableCredential.extend() checks credentialSubject content for validity

### ISSUE THREAD

**Issue by adrian-grassl** [iotaledger/identity.rs#429]
## Bug description
- When adding the credentialSubject to a VC with `VerifiableCredential.extend()` and use the key `id` in the passed credentialSubject object, there seems to be a validity check, if the value in that key is a valid did string
- Only a string with a colon will be accepted in the key `id`
- This will be accepted `{ id: 'abc:' }`
- This will not `{ id: 'abc' }`

## Language version
What programming language are you using? Rust or one of the bindings?
Which version of the language are you running?
- Language: WASM
- Version: [NPM Package 0.3.11](https://www.npmjs.com/package/@iota/identity-wasm/v/0.3.11)

## IOTA Identity version
Which version of IOTA Identity are you using?
- 0.3.11

## Steps To reproduce the bug
Explain how the maintainer can reproduce the bug.
- See Bug description above

## Expected behaviour
- As long as the content of the credentialSubject is a valid JSON object, there shouldn't be any further validity checks

## Actual behaviour
- See Bug description above

## Errors
- Unfortunately the returned error doesn't hint at the problem at all
- `createVerifiableCredential DecodeJSON: Failed to decode JSON: data did not match any variant of untagged enum OneOrMany`

**Comment by abdulmth** [comment]
I think the library checks if the `id` is a valid `URI` which is specified in the W3C standard [here](https://www.w3.org/TR/vc-data-model/#credential-subject).

>Each [credentialSubject] object MAY contain an id, as described in Section § 4.2 Identifiers.

 and in Section § 4.2 it states: 

>  The value of the id property MUST be a URI.

Maybe @JelleMillenaar can quickly double-check, otherwise we might close this issue.

**Comment by cycraig** [comment]
We can probably just parse it with regex and wrap it in a string since we don't need to extract any of the parts explicitly.

The DID Test Suite just uses regex and RFC3986 provides an expression: https://datatracker.ietf.org/doc/html/rfc3986#appendix-B

https://github.com/w3c/did-test-suite/blob/1b86f694ad40e0b61472f02e8cd06a200ac2b4f9/packages/jest-did-matcher/src/matchers/toBeValidUri/predicate.js#L4

```js
    // URI Regex is from RFC3986 Appendix B
    const uriRegex =
    /^(([^:\/?#]+):)?(\/\/([^\/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?/;
```

**Comment by abdulmth** [comment]
We decided to keep the validation as a URL.
