### ISSUE TITLE
[Bug] Service definition does not match DID spec for type and serviceEndpoint

### ISSUE THREAD

**Issue by obany** [iotaledger/identity.rs#447]
## Bug description
The definition of the service type currently defines the `type` field as a string, and the `serviceEndpoint` as a Url
https://github.com/iotaledger/identity.rs/blob/8a97e95ae549c5e78d32336739eb349f49e977f8/identity-did/src/service/service.rs#L25-L27

The spec defines these properties to also allow set of elements
https://www.w3.org/TR/did-core/#service-properties

## Expected behaviour
The service type should match the spec.

## Actual behaviour
The service type only supports single strings.

**Comment by obany** [comment]
In our case we store a set, with alternative endpoints to query if one is down.

**Comment by cycraig** [comment]
A `Service` now allows ordered sets and maps for the `serviceEndpoint` field but not nested maps. This change is currently only on the dev branch until the next version release.

Sample code using the Wasm bindings to add a new `Service` with a set of endpoints:

```js
let serviceJSON = {
  id: doc.id + "#linked-domain",
  type: "LinkedDomains",
  serviceEndpoint: ["https://iota.org/", "https://example.com/"],
};
doc.insertService(Service.fromJSON(serviceJSON));
```

or with a map:

```js
let serviceJSON = {
  id: doc.id + "#linked-domain",
  type: "LinkedDomains",
  serviceEndpoint: {
    "origins": ["https://iota.org/", "https://example.com/"]
  },
};
doc.insertService(Service.fromJSON(serviceJSON));
```

Please comment here or open a new issue if there are any problems. Thank you.

**Comment by 7opf** [comment]
@cycraig are there plans to support sets of strings for the `type`? We have no need for it at the moment, but I came across a comment in our code regarding this issue from @obany.

**Comment by cycraig** [comment]
> are there plans to support sets of strings for the type?

I forgot that was even a problem! Thanks for the report, will open a PR for it SoonTM.
