### ISSUE TITLE
[Bug] ProofVerificationMethod do not reference the whole key name

### ISSUE THREAD

**Issue by sdellava** [iotaledger/identity.rs#457]
## Bug description
When signing a Document using a DID key, the ProofVerificationMethod include only the suffix of the controller key name.
This is normally not a issue if the DID has only one controller (in the Authentication controller list) but if one need to add more controllers to the Document the key used in the proof need to be fully qualified (did + # + key suffix)
Missing the DID part lead to a invalid document.

In example, this DID has tre versions, but the explorer shows only two: 

[link to exploer](https://explorer.iota.org/mainnet/identity-resolver/did:iota:9qfPEAcRH15kMKCg5ovRRBk9pSusZuVWeXwhUgKbS6pi?debugview=true)

In the second I've added a new controller in and singed whit the first controller key. The third version can be seen 

[here:](https://explorer.iota.org/mainnet/identity-resolver/did:iota:9qfPEAcRH15kMKCg5ovRRBk9pSusZuVWeXwhUgKbS6pi?debugview=true)

This version is signed with the second controller key, but being the key indicated only with "#key" I guess the lib use the key of the first controller to check validate the signature.

I've also used different suffix for the two keys (#key for the first controller, #key2 for the second) but nothing changed, so it seems that the lib use the subject did ad key selector.
 
## Language version
- Language: wasm

## IOTA Identity version
Which version of IOTA Identity are you using?  v0.3.0 

## Steps To reproduce the bug
Explain how the maintainer can reproduce the bug.

1. create a did
2. create a second controller did
2. add an authentication method for the second controller to the subject's did.document
3. sing with the subject's key
4. publish the new document
5. sing the document with the new controller's key
6. publish the document

## Expected behavior
I expect the did to be resolved and find the signature provided by the new controller

## Actual behavior
did do not resolve the last version of the Document

**Comment by cycraig** [comment]
This was mostly addressed with the changes in #458 but #623 will allow the case where the controller method added to the document shares the same fragment as an existing method.
