### ISSUE TITLE
Support to multiple controllers and controller handover

### ISSUE THREAD

**Issue by sdellava** [iotaledger/identity.rs#465]
## Description
The W3C DID standard states that a Subject/DID Document may have multiple controllers. 

## Motivation
This feature is very important for differentiating the roles of controllers using verifiable credentials.
It is also very useful for implementing the concept of "ownership" of an object identified by a DID: its controller is its owner. 
It is therefore very important that IOTA Identity implements this part of the standard by ensuring that multiple controllers can be assigned to a Subject and that a new controller can take over from the previous one (ownership handover).
The onweship handover is very important for NFT. Today the common way to assign the ownership of an object identified by a unique token (NFT) is to send it to a new owner's address, but the addresses do not actually represent the owner, but rather who controls the private key. This can change hands without evidence and this makes the NFT model unsuitable for applications on real (non-digital) goods.

Using DID and being able to manage a handover, the constructor of the object (physical or digital) can assign a DID and then assign to the buyer the ownership of the object making it become the controller of the DID.  The object can still be represented by a token that is minted. Using the same keys used to create the DID of the creator of the object, you get a unique address linked to the original creator and owner who can decide to send the token to an address specified by the new owner or define it only the controller of the DID of the object. This second case allows you to represent the loan of objects, without the need to use a smartcontract
 
DIDs can be assigned verifiable credentials that make real the identity of the creators and owners of the objects.  

## Requirements
Write a list of what you want this feature to do.

1. add more controllers
2. allow a controller to remove himeself from a document
3. allow a controller to remove other controllers form a document

## Are you planning to do it yourself in a pull request?

No

**Comment by JelleMillenaar** [comment]
Will be implemented with #306 and is therefore a duplicate. Thanks for the additional info!
