### ISSUE TITLE
[Bug] NodeJS Binding should not polyfill fetch if it already exists

### ISSUE THREAD

**Issue by obany** [iotaledger/identity.rs#482]
## Bug description
The nodejs always polyfills `fetch` even if it already has been https://github.com/iotaledger/identity.rs/blob/6a5f4d317740be6f914b55f36beda0008c62e758/bindings/wasm/build/node.js#L13 

## Language version
JS Node WASM bindings

## IOTA Identity version
0.4.0

## Steps To reproduce the bug
Explain how the maintainer can reproduce the bug.

1. Polyfill fetch with custom library
2. Load identity wasm
3. Fetch polyfill is overwritten

## Expected behaviour
Original polyfill should be retained.

## Actual behaviour
Original polyfill is overwritten.

**Comment by obany** [comment]
This fix that has been merged for this won't work if another library has already polyfilled fetch, it will overwrite it.

Instead of introducing the `global.is_fetch_polyfilled` flag, just check for `global.fetch` being undefined.

**Comment by eike-hass** [comment]
Hi @obany thank you for your feedback, we trying to solve compatibility with multiple version of the library for now. For general compatibility with multiple node-fetch versions we are awaiting the outcome of https://github.com/node-fetch/node-fetch/issues/1317

**Comment by obany** [comment]
Can you re-open this issue then, as it is not fixed by the linked PR

**Comment by eike-hass** [comment]
reopening the issue to evaluate a complete solution

**Comment by eike-hass** [comment]
@obany apologies, I thought this was related to another report we had where multiple versions of identity-wasm were causing the issue. Can you provide some more information on polyfills used, the build setup and such? maybe link to the project if it is open source?

**Comment by eike-hass** [comment]
Fixed in versions 0.4.2 and 0.5.0-dev.2 on npm
