### ISSUE TITLE
[Task] Refactor `MethodSecret` for better key collection support

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/identity.rs#568]
## Description

Refactor the `MethodSecret` type and the places where it is used, i.e. `Update::CreateMethod` and `IdentitySetup`. Implementation of this issue may have to wait for #539 to be completed.

One approach would be to combine `MethodType` and `MethodSecret` in the two mentioned usages, to allow for fine-grained control over the generation process, particularly for key collections.

```rust
pub enum MethodSecret {
  // This would be the default
  GenerateEd25519,
  Ed25519(PrivateKey),
  GenerateMerkleKeyCollection(usize, KeyType),
  MerkleKeyCollection(KeyCollection),
}
```

This allows users to specify size and key type for the key collection generation. Generally, each non-collection type would have two entries in the enum. One for generation in a `Storage` implementation, and one for providing a pre-existing secret.

## Motivation

When creating a method, one can specify the `MethodType` and an optional `MethodSecret`. If the `MethodSecret` is `None`, a key or key collection of the `MethodType` is generated. In case of `MethodType::MerkleKeyCollection2021`, it is unclear what the default value for the collection size would be. It is not possible to explicitly specify the size or of what `KeyType` the collection should be. One would have to generate their own collection and pass it in via `MethodSecret`. This is undesirable in some cases, since keys are exposed in memory rather than generated in stronghold.

## To-do list
Create a task-specific to-do list . Please link PRs that match the To-do list item behind the item after it has been submitted.

- [ ] Item one
- [ ] Item two
- [ ] Item three

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by abdulmth** [comment]
Probably important issue for the Account WASM bindings.

**Comment by cycraig** [comment]
Related to issue #646 .

Might be made redundant by #715.

**Comment by cycraig** [comment]
No longer an issue: `KeyCollection` was removed in #715.
