### ISSUE TITLE
[Request] Embed library version in metadata

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#589]
## Description
Explore whether storing the identity library version used to publish/update a DID in its metadata is worthwhile.

## Motivation
For applications such as the explorer identity-resolver which may deal with incompatible versions of IOTA DIDs (legacy and current) with structural changes, it might be useful to store the library version used to publish/update the DID in its metadata.

It may also be useful for debugging identities and migrating them to new versions, otherwise we rely on being able to discern structural changes between incompatible versions.

NOTE: this is completely separate from the DID message version, which is a marker used for decoding messages from the Tangle.

## Requirements

- Identify which version of the IOTA `identity` library was used to generate/update a DID Document

## Open questions (optional)

1. Is this worth the extra bytes on every DID Document?
1. What if developers want to exclude the version from their DID Document? Would we support that and how would our API enable that? 
1. Is the feature still worthwhile if not every DID Document includes it? Either if a developer removes the version or if dealing with an older identity from before the introduction of versioning?
1. How would we manage the version between different bindings when they are not kept in lock-step, make them all use the Rust library version?
1. Is there a better alternative? Maybe we could add a function which attempts to return the version based on a JSON serialisation of a DID Document?
1. Instead of storing the library version, should we have a DID Document "structure" version similar to DID message version? This would only be incremented when a breaking change to the layout of a DID Document or its Metadata occurs, and would  be the same across all bindings.

**Comment by eike-hass** [comment]
Decided against embedding the library version, since it would create and additional layer of versioning, that is not covered by the spec and hard to implement outside the library.
