### ISSUE TITLE
[Request] Provide a public API for using a given verification method to verify signed data. 

### ISSUE THREAD

**Issue by olivereanderson** [iotaledger/identity.rs#615]
## Description
We currently have a private associated function `CoreDocument::do_verify` that uses a given verification method to verify signed data. We would like to make this functionality part of our public API, but the question is where this method should live since it is arguably not very natural to (directly) associate this with `CoreDocument`. One alternative would be to make it a method on `VerificationMethod`, but it is not clear whether this is natural with regards to how `VerificationMethod` is used. 

## Motivation
This addition allows for more flexibility with regards to signature verification. 

## Requirements
Write a list of what you want this feature to do.

1. Allow verifying signed data using a given verification method. 

## Are you planning to do it yourself in a pull request?
No, but if no one else is interested in tackling this I would be happy to work on it.

**Comment by eike-hass** [comment]
Will be tackled as part of a more general cryptographic agility effort.
