### ISSUE TITLE
[Request] Allow creating methods by public key in `Account`, Wasm bindings

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#646]
## Description
The low-level API allows creating an `IotaVerificationMethod` by a public key alone, namely the `from_did` method:

```rust
/// Creates a new [`IotaVerificationMethod`] from the given `did` and `keypair`.
pub fn from_did(did: IotaDID, key_type: KeyType, public_key: &PublicKey, fragment: &str) -> Result<Self> 
```

The `Account` and Wasm bindings should be updated to expose similar functionality.

In particular, the `WasmVerificationMethod::fromDID` method still uses a `KeyPair` rather than just the public key:
```rust
/// Creates a new `VerificationMethod` object from the given `did` and `key`.
#[wasm_bindgen(js_name = fromDID)]
pub fn from_did(did: &WasmDID, key: &KeyPair, fragment: String) -> Result<WasmVerificationMethod, JsValue>
```

The `Account` `CreateMethod` update builder also only allows inputting a secret, or generating one automatically:

```rust
CreateMethod {
  scope: MethodScope,
  type_: MethodType,
  fragment: String,
  method_secret: Option<MethodSecret>,
},
```

## Motivation
There are several use-cases for creating a `VerificationMethod` where one would not have access to the underlying private key to create a `KeyPair`:

- in a distributed setting where the private key is not on the device updating the DID Document, e.g. IoT devices, phone apps, controllers etc.
- when enabling another party to update your DID Document without accessing their private key, i.e. controller workaround.

Furthermore the private key in the `KeyPair` is usually completely unnecessary, and `KeyPair` is just used out of convenience since it wraps both the public key and the key type in one.

The `Account` does not actually need to store the private key in either of the above scenarios since the signer is another entity, and trying to sign with that method should just throw an error if the key is not present, which is fine.

## Requirements

1. ~~Update `WasmVerificationMethod::fromDID` method to match the `IotaVerificationMethod::from_did` parameters.~~ Done in #655 
2. Alter the `CreateMethod` update builder for the `Account` to allow creating methods with just a public key.

## Open questions (optional)
Is there a convenient design for `CreateMethod` to take either a `MethodSecret` or `PublicKey` (+ `KeyType`) without conflicting at runtime? Another enum level perhaps?

## Are you planning to do it yourself in a pull request?

If no-one else picks this up.

**Comment by cycraig** [comment]
Note also issue #568 regarding `MethodSecret` in the `Account`.

**Comment by cycraig** [comment]
For the `Account` I'm thinking of replacing `MethodSecret` with an enum that allows either a `PublicKey` or `PrivateKey` entry, possibly using a Typescript discriminating union in the Wasm bindings.

This may not be future-proof depending on the verification methods we may introduce, but it works for most of those listed in the [DID Specification Registry](https://www.w3.org/TR/did-spec-registries/#verification-method-types) such as `Ed25519` and `X25519` (not for those with JWK representations but we don't support those anyway).

Ideally whatever is chosen would not duplicate the `MethodType` field. Maybe we could roll it into the enum variants? It's a bit messy to represent three options, however.

E.g.
```rust
enum MethodContent {
  Ed25519New, // generate and store new Ed25519 key
  Ed25519Private(PrivateKey),
  Ed25519Public(PublicKey),
  X25519New, // generate and store new X25519 key
  X25519Private(PrivateKey),
  X25519Public(PublicKey),
  ExoticNew(Any, Special, Arguments),
  ExoticPrivate(FancyPrivateRepresentation),
  ExoticPublic(FancyPublicRepresentation),
  // ... can be extended with any new method we add.
}

// Note the type is now implicit in the MethodContent.
account
  .create_method()
  .scope(VerificationMethod)
  .fragment("#key-1")
  .content(MethodContent::Ed25519Public(public_key))
  .apply()
  .await?;
```

Another alternative would be three classes of nested enums for `New/Generate`, `Private`, and `Public`.

E.g.

```rust
enum MethodContent {
  New/Generate(MethodArguments),
  Insert/Private(MethodPrivate),
  Public(MethodPublic),
}

enum MethodArguments {
  Ed25519,
  X25519,
  Exotic(Any, Special, Arguments),
}

enum MethodPrivate {
  Ed25519(PrivateKey),
  X25519(PrivateKey),
  Exotic(FancyPrivateRepresentation),
}

enum MethodPublic {
  Ed25519(PublicKey),
  X25519(PPublicKey),
  Exotic(FancyPublicRepresentation),
}

// Slightly more cumbersome to use.
account
  .create_method()
  .scope(VerificationMethod)
  .fragment("#key-1")
  .content(MethodContent::Private(MethodPrivate::Ed25519(private_key)))
  .apply()
  .await?;
```

**Comment by PhilippGackstatter** [comment]
I think Option 1 is my favourite. I also thought in that direction when introducing the `MethodSecret`, and while verbose, I still think it (option 1) is the most flexible and extensible approach. Option 2 could be trimmed down to be represented as a struct:

```rust
pub struct MethodContent {
   // Probably has to be different from the existing KeyType type.
   type_: KeyType,
   material: KeyMaterial,
}

pub enum KeyMaterial {
    Generate,
    Private(PrivateKey),
    Public(PublicKey)
}
```

which would only require adding one variant per "key type". Though I assume that, as you implicitly designed, some future key types may require arguments for their construction that cannot be represented with this approach, such as how we would've needed a size argument for key collections. Thus, for flexibility the verbosity of option 1 might be needed.

Terminology-wise I prefer `Generate` over `New` simply because it's more specific. `Private` and `Public` prefixes seem good in the variants.

**Comment by olivereanderson** [comment]
I prefer Option 2, but with a slight modification. Instead of using `content(arg: MethodContent) -> CreateMethodBuilder` I would prefer to remove the top level `MethodContent` enum and instead have three different methods on the builder: 
```
generate_method_content(arg: MethodArguments) -> CreateMethodBuilder;
private_method_content(arg: MethodPrivate) -> CreateMethodBuilder; 
public_method_content(arg: MethodPublic) -> CreateMethodBuilder; 
```
I am also fine with Option 1 as long as it is supported with good documentation.

**Comment by cycraig** [comment]
The problem with `KeyMaterial` is indeed, as you mentioned, that it assumes every `KeyType` we support will have the same `PrivateKey`/`PublicKey` representation and require no further input parameters for generation. 

It works right now if we remove `MerkleKeyCollection`. However, I think it's likely that future verification methods will require different arguments and key representations, hence we'll have to deal with this problem eventually.

Option 1 with slightly different naming scheme:
```rust
enum MethodContent {
  /// Generate and store new Ed25519 key.
  GenerateEd25519,
  /// Store a private Ed25519 key and derive the public key from it.
  PrivateEd25519(PrivateKey),
  /// Insert a public Ed25519 key into the new verification method directly,
  /// without generating or storing a private key.
  PublicEd25519(PublicKey),

  GenerateX25519, 
  PrivateX25519(PrivateKey),
  PublicEd25519(PublicKey),

  GenerateExotic(Any, Special, Arguments),
  PrivateExotic(FancyPrivateRepresentation),
  PublicExotic(FancyPublicRepresentation),

  // ... can be extended with any new method we add.
}
```

**Comment by cycraig** [comment]
> I would prefer to remove the top level MethodContent enum and instead have three different methods on the builder:

That introduces methods that conflict with each other at runtime, and in the Wasm bindings they would exist alongside each other in the parameters. E.g.

```ts
account.createMethod({
  fragment: "asdf",
  generateMethodContent: ...
  privateMethodContent: ...
  publicMethodContent: ...
})
``

This would cause a runtime error or silently ignoring some of the options.

**Comment by olivereanderson** [comment]
> ```
await account.createMethod({
  fragment: "asdf",
  generateMethodContent: ...,
  privateMethodContent: ...,
  publicMethodContent: ...
})
```
If this is how it works in Wasm then that is indeed problematic.  Out of interest however can't you introduce the same problem in Rust with option one by calling `content` repeatedly with different arguments? 

It is also possible to use generics to make it impossible to call say `private_method_content` after say `generate_method_content`, but that doesn't translate well to the bindings of course. 

If the alternative of splitting `content` into three different methods is not feasible then I would indeed prefer Option 1 (with the slightly different naming scheme from your previous comment) over (the original) Option 2.

**Comment by cycraig** [comment]
> Out of interest however can't you introduce the same problem in Rust with Option 1 by calling content repeatedly with different arguments?

No, it would just take the last input for that field.

E.g.

```rust
account
  .create_method()
  .fragment("asdf")
  .fragment("thisOneIsUsed")
  .content(GenerateEd25519)
  .content(GenerateX25519) // <-- this one is used
  .apply()
  .await?;
```

This is the case with all builders.

E.g.

```rust
ClientBuilder::new()
  .encoding(DIDMessageEncoding::JSONBrotli)
  .encoding(DIDMessageEncoding::JSON) // <-- this one it used.
```

> It is also possible to use generics to make it impossible to call say private_method_content after say generate_method_content, but that doesn't translate well to the bindings of course.

Indeed, and that likely would not translate to other bindings either.
