### ISSUE TITLE
Add proper documentation for Code Editor Preview

### ISSUE THREAD

**Issue by huhn511** [iotaledger/identity.rs#71]
Today's code editors show possible functions with some examples, how to use it. 

Goal: The library should show, which attributes by name. and types are needed for a function.  

This is the current state:
![unknown-1](https://user-images.githubusercontent.com/10562055/98543934-81506a80-2293-11eb-8f78-7c7b6b4a9392.png)

This is how it should look like:
![intellisense](https://user-images.githubusercontent.com/10562055/98544441-4ef33d00-2294-11eb-852f-ee819821fc3a.gif)

**Comment by Thoralf-M** [comment]
Should work now with https://github.com/iotaledger/identity.rs/pull/42/commits/475f6d0333a8bc506ab1aacdc9c25f51d0d2dba7
