### ISSUE TITLE
[Task] Feature-gate the diff module in identity-iota-core

### ISSUE THREAD

**Issue by HenriqueNogara** [iotaledger/identity.rs#710]
## Description
Assess the need of feature-gating the diff module in identity-iota-core.

## Motivation
Increase flexibility of the crate.

## Resources
[Pr review comment](https://github.com/iotaledger/identity.rs/pull/693#discussion_r821576194)

## Change checklist
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] The feature or fix is implemented in Rust and across all bindings whereas possible.
- [ ] The feature or fix has sufficient testing coverage
- [ ] All tests and examples build and run locally as expected
- [ ] Every piece of code has been document according to the documentation guidelines.
- [ ] If conceptual documentation (mdbook) and examples highlighting the feature exist, they are properly updated.
- [ ] If the feature is not currently documented, a documentation task Issue has been opened to address this.

**Comment by cycraig** [comment]
This will be made redundant if we decide to go ahead and remove the diff chain and `identity-diff` crate altogether. I think this can be closed for now.
