### ISSUE TITLE
Handle "main" network as default more consistently

### ISSUE THREAD

**Issue by JelleMillenaar** [iotaledger/identity.rs#72]
A DID Document that is created without a network defaults to the mainnet called "main". The main part is left out of the id and keys. Such that they are did:iota:uuid instead of did:iota:main:uuid. However, if I input "main" into the generate key function, it does add main into the did's such that they render did:iota:main:uuid. Even though they work the same, this creates an inconsistent DID Document. I suggest we handle main as a default input better such that no input or "main" as network input is handled the same.

**Comment by l1h3r** [comment]
Which version is considered the canonical version, `did:iota:uuid` or `did:iota:main:uuid`? (which should be in the document)

**Comment by JelleMillenaar** [comment]
Inside a DID Document it should be stored as `did:iota:uuid` with the assumption that with no network found the mainnet is assumed as is described in the DID Method Specification.

**Comment by l1h3r** [comment]
This was resolved in #73
