### ISSUE TITLE
[Doc] Stardust Updates

### ISSUE THREAD

**Issue by charlesthompson3** [iotaledger/identity.rs#773]
## Description
With the upcoming changes, some articles in the documentation may require updates and versioning.

We need to be able to launch products with their respective docs to improve the overall developer experience.

## Reference material
Links resources such as RFCs, specifications, and other documentation. 

## To-do List
The following pages may require updating. Please feel free to add or remove any items you see fit.

- Contribute, Contact, and FAQ for standardization
- Glossary (for potential incorporation with the main wiki glossary)

To what extent I can, I would make a PR to incorporate these updates, but the @iotaledger/tech-writers team will require support from the developers to know exactly what should be updated.

**Comment by lucas-tortora** [comment]
Parent issue: https://github.com/iotaledger/stardust-project/issues/45
