### ISSUE TITLE
[Task] Release to crates.io

### ISSUE THREAD

**Issue by eike-hass** [iotaledger/identity.rs#869]
## Description
In order to release to crates.io we need rename our packages and setup the automatic release process.

## To-do list

- [x] Rename crates - #895
- [x] Exclude `examples` (see https://github.com/iotaledger/identity.rs/runs/6837111260?check_suite_focus=true where examples would be published) - #895
- [x] Publish crates.
- [ ] setup CI to push automatically

**Comment by cycraig** [comment]
Still need to rename packages and actually release.

**Comment by cycraig** [comment]
I've added `release = false` to the `examples` package per the `cargo-release` FAQ: https://github.com/crate-ci/cargo-release/blob/c2f0d52a1c1a02cf1fdc6e68106954111f7e2c56/docs/faq.md#why-does-publishfalse-still-release

> ## Why does publish=false still release?
> publish only controls whether to publish to crates.io. Some programs might want version bumping, tagging, replacements, etc without publishing.
> 
> If you do want to disable everything, set release = false.

**Comment by cycraig** [comment]
I don't think `cargo-release` was going to publish `examples` either way, it does distinguish `release` from `publish` specifically, and it says `release` in the logs:

```
Release
  identity-diff-derive 0.6.0
  identity-diff 0.6.0
  identity-core 0.6.0
  identity-did 0.6.0
  identity-iota-core 0.6.0
  identity-account-storage 0.6.0
  identity-credential 0.6.0
  identity-iota 0.6.0
  identity-account 0.6.0
  identity 0.6.0
  examples 0.6.0
```

**Comment by eike-hass** [comment]
Let's look at at automatic publishing separately.
