### ISSUE TITLE
[Task] Find a new tool for license header checks

### ISSUE THREAD

**Issue by olivereanderson** [iotaledger/identity.rs#921]
## Description
The unstable [`license_template_path`](https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#license_template_path) from `rustfmt` was removed [in this PR](https://github.com/rust-lang/rustfmt/pull/5357). Since we rely on this option a replacement will have to be found. 

@grtlr is working on [`cargo-license-template`](https://crates.io/crates/cargo-license-template) which is intended to provide comparable functionality, however it is not yet ready to be used for identity.rs as it currently errors on .rs files in the target directories of sub-projects (such as `bindings/stronghold-nodejs`). @grtlr is aware of this issue and will hopefully soon be able to solve it and we can of course also offer to help.

**Comment by cycraig** [comment]
Fantastic. With `v0.1.3` it suffices to add a `.license_template_ignore` file to ignore the `libjose` fixtures for now.

```
libjose/tests/fixtures/
```

Alternatively a change similar to #917 could be applied for the following files:
```
libjose/tests/fixtures/rfc7797.rs ... failed
libjose/tests/fixtures/rfc8037_ed25519.rs ... failed
libjose/tests/fixtures/rfc7518.rs ... failed
libjose/tests/fixtures/rfc7638.rs ... failed
libjose/tests/fixtures/rfc8037_x448.rs ... failed
libjose/tests/fixtures/rfc8037_x25519.rs ... failed
libjose/tests/fixtures/rfc7516.rs ... failed
libjose/tests/fixtures/rfc7517.rs ... failed
libjose/tests/fixtures/rfc7515.rs ... failed
```
Either way we should add `cargo-license-template` to GitHub Actions.
