### ISSUE TITLE
[Task] Expose DID trait in bindings.

### ISSUE THREAD

**Issue by HenriqueNogara** [iotaledger/identity.rs#973]
## Description
Expose DID trait in bindings.

## Motivation
Allow users to add their custom DID implementation.

**Comment by cycraig** [comment]
The comment https://github.com/iotaledger/identity.rs/pull/968#discussion_r940741266 was specifically on adding the `DID` trait methods to the `WasmCoreDID` struct (`scheme()`, `authority()`, `method()`, etc.) to match the methods of `WasmIotaDID` and `WasmStardustDID`. It's still unclear how we would achieve custom DID implementations in Wasm.

**Comment by eike-hass** [comment]
Solved in #994.
